<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="resolutionmodels" nsURI="http://www.hyperflex.org/resolutionmodels"
    nsPrefix="resolutionmodels">
  <eClassifiers xsi:type="ecore:EClass" name="ResolutionModel">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="resolutionElements" lowerBound="1"
        upperBound="-1" eType="#//RMResolutionElement" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="featureModel" lowerBound="1"
        eType="ecore:EClass ../../org.hyperflex.featuremodels.model/models/featureModel.ecore#//FeatureModel"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="templateSystemModel" lowerBound="1"
        eType="#//TemplateSystemModel" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RMResolutionElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="transformations" upperBound="-1"
        eType="#//RMTransformation" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requiredElements" eType="#//RMRequiredElements"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="feature" lowerBound="1"
        eType="ecore:EClass ../../org.hyperflex.featuremodels.model/models/featureModel.ecore#//Feature"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="activeIfSelected" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="TRUE"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RMTransformation" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RMRequiredElements" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="RMTransfImplementation" abstract="true"
      eSuperTypes="#//RMTransformation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="classNamespace" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="className" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RMTransfProperty" abstract="true" eSuperTypes="#//RMTransformation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RMTransfConnection" abstract="true"
      eSuperTypes="#//RMTransformation"/>
  <eClassifiers xsi:type="ecore:EClass" name="TemplateSystemModel" abstract="true"/>
</ecore:EPackage>
