<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="roscomponentmodel" nsURI="http://www.hyperflex.org/componentmodels.ros"
    nsPrefix="roscomponentmodel">
  <eClassifiers xsi:type="ecore:EClass" name="Composite" eSuperTypes="#//AbstractComponent">
    <eStructuralFeatures xsi:type="ecore:EReference" name="components" upperBound="-1"
        eType="#//AbstractComponent" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="msgProducers" upperBound="-1"
        eType="#//CompositeMsgProducer" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="msgConsumers" upperBound="-1"
        eType="#//CompositeMsgConsumer" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="topics" upperBound="-1"
        eType="#//Topic" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="srvProducers" upperBound="-1"
        eType="#//CompositeSrvProducer" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="srvConsumers" upperBound="-1"
        eType="#//CompositeSrvConsumer" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="wires" upperBound="-1"
        eType="#//Wire" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1"
        eType="#//CompositeProperty" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Node" eSuperTypes="#//AbstractComponent">
    <eStructuralFeatures xsi:type="ecore:EReference" name="msgProducers" upperBound="-1"
        eType="#//NodeMsgProducer" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="msgConsumers" upperBound="-1"
        eType="#//NodeMsgConsumer" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
        eType="#//NodeProperty" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="srvProducers" upperBound="-1"
        eType="#//NodeSrvProducer" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="srvConsumers" upperBound="-1"
        eType="#//NodeSrvConsumer" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="packageName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NodeMsgProducer" eSuperTypes="#//NodeMsgInterface"/>
  <eClassifiers xsi:type="ecore:EClass" name="NodeMsgConsumer" eSuperTypes="#//NodeMsgInterface"/>
  <eClassifiers xsi:type="ecore:EClass" name="CompositeMsgProducer" eSuperTypes="#//CompositeMsgInterface"/>
  <eClassifiers xsi:type="ecore:EClass" name="CompositeMsgConsumer" eSuperTypes="#//CompositeMsgInterface"/>
  <eClassifiers xsi:type="ecore:EClass" name="Topic">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Property">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SrvProducer">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SrvConsumer">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CompositeSrvProducer" eSuperTypes="#//SrvProducer">
    <eStructuralFeatures xsi:type="ecore:EReference" name="promote" eType="#//SrvProducer"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NodeSrvProducer" eSuperTypes="#//SrvProducer">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="srvName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CompositeSrvConsumer" eSuperTypes="#//SrvConsumer">
    <eStructuralFeatures xsi:type="ecore:EReference" name="promote" eType="#//SrvConsumer"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NodeSrvConsumer" eSuperTypes="#//SrvConsumer">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="srvName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Wire">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="#//SrvProducer"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="#//SrvConsumer"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="System">
    <eStructuralFeatures xsi:type="ecore:EReference" name="composite" lowerBound="1"
        eType="#//Composite" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MsgInterface">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="connection" eType="#//Topic"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CompositeMsgInterface" eSuperTypes="#//MsgInterface">
    <eStructuralFeatures xsi:type="ecore:EReference" name="exposed" lowerBound="1"
        eType="#//Topic"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NodeMsgInterface" eSuperTypes="#//MsgInterface">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="topicName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractComponent" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NodeProperty" eSuperTypes="#//Property">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CompositeProperty" eSuperTypes="#//Property">
    <eStructuralFeatures xsi:type="ecore:EReference" name="exposed" lowerBound="1"
        eType="#//Property"/>
  </eClassifiers>
</ecore:EPackage>
