<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="roscompositionmodel" nsURI="http://robotics.unibg.it/compositionmodels.ros"
    nsPrefix="roscompositionmodel">
  <eClassifiers xsi:type="ecore:EClass" name="ROSComposite" eSuperTypes="../../org.hyperflex.compositionmodels.model/models/compositionModel.ecore#//Composite">
    <eStructuralFeatures xsi:type="ecore:EReference" name="composite" lowerBound="1"
        eType="ecore:EClass ../../org.hyperflex.compositionmodels.model/models/compositionModel.ecore#//Composite"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ROSMsgProducer" eSuperTypes="../../org.hyperflex.compositionmodels.model/models/compositionModel.ecore#//CompProvidedInterf">
    <eStructuralFeatures xsi:type="ecore:EReference" name="msgProducer" lowerBound="1"
        eType="ecore:EClass ../../org.hyperflex.componentmodels.ros.model/models/rosComponentModel.ecore#//CompositeMsgProducer"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ROSMsgConsumer" eSuperTypes="../../org.hyperflex.compositionmodels.model/models/compositionModel.ecore#//CompRequiredInterf">
    <eStructuralFeatures xsi:type="ecore:EReference" name="msgConsumer" lowerBound="1"
        eType="ecore:EClass ../../org.hyperflex.componentmodels.ros.model/models/rosComponentModel.ecore#//CompositeMsgConsumer"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ROSSrvProducer" eSuperTypes="../../org.hyperflex.compositionmodels.model/models/compositionModel.ecore#//CompProvidedInterf">
    <eStructuralFeatures xsi:type="ecore:EReference" name="srvProducer" lowerBound="1"
        eType="ecore:EClass ../../org.hyperflex.componentmodels.ros.model/models/rosComponentModel.ecore#//CompositeSrvProducer"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ROSSrvConsumer" eSuperTypes="../../org.hyperflex.compositionmodels.model/models/compositionModel.ecore#//CompRequiredInterf">
    <eStructuralFeatures xsi:type="ecore:EReference" name="srvConsumer" lowerBound="1"
        eType="ecore:EClass ../../org.hyperflex.componentmodels.ros.model/models/rosComponentModel.ecore#//CompositeSrvConsumer"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RosTopic" eSuperTypes="../../org.hyperflex.compositionmodels.model/models/compositionModel.ecore#//Connection"/>
  <eClassifiers xsi:type="ecore:EClass" name="ROSProperty" eSuperTypes="../../org.hyperflex.compositionmodels.model/models/compositionModel.ecore#//Property">
    <eStructuralFeatures xsi:type="ecore:EReference" name="property" eType="ecore:EClass ../../org.hyperflex.componentmodels.ros.model/models/rosComponentModel.ecore#//CompositeProperty"/>
  </eClassifiers>
</ecore:EPackage>
