<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="rosresolutionmodels" nsURI="http://www.hyperflex.org/resolutionmodels.ros"
    nsPrefix="rosresolutionmodels">
  <eClassifiers xsi:type="ecore:EClass" name="ROSTransfImplementation" eSuperTypes="../../org.hyperflex.resolutionmodels.model/models/resolutionModel.ecore#//RMTransfImplementation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetNode" lowerBound="1"
        eType="ecore:EClass ../../org.hyperflex.componentmodels.ros.model/models/rosComponentModel.ecore#//Node"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ROSTransfProperty" eSuperTypes="../../org.hyperflex.resolutionmodels.model/models/resolutionModel.ecore#//RMTransfProperty">
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetProperty" lowerBound="1"
        eType="ecore:EClass ../../org.hyperflex.componentmodels.ros.model/models/rosComponentModel.ecore#//Property"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ROSTransfConnection" eSuperTypes="../../org.hyperflex.resolutionmodels.model/models/resolutionModel.ecore#//RMTransfConnection">
    <eStructuralFeatures xsi:type="ecore:EReference" name="newConnections" lowerBound="1"
        upperBound="-1" eType="#//ROSConnection" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ROSConnection" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ROSTopicConnection" eSuperTypes="#//ROSConnection">
    <eStructuralFeatures xsi:type="ecore:EReference" name="topic" lowerBound="1" eType="ecore:EClass ../../org.hyperflex.componentmodels.ros.model/models/rosComponentModel.ecore#//Topic"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="messageInterface" lowerBound="1"
        eType="ecore:EClass ../../org.hyperflex.componentmodels.ros.model/models/rosComponentModel.ecore#//MsgInterface"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ROSServiceConnection" eSuperTypes="#//ROSConnection">
    <eStructuralFeatures xsi:type="ecore:EReference" name="serviceProducer" lowerBound="1"
        eType="ecore:EClass ../../org.hyperflex.componentmodels.ros.model/models/rosComponentModel.ecore#//SrvProducer"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="serviceConsumer" lowerBound="1"
        eType="ecore:EClass ../../org.hyperflex.componentmodels.ros.model/models/rosComponentModel.ecore#//SrvConsumer"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ROSRequiredElements" eSuperTypes="../../org.hyperflex.resolutionmodels.model/models/resolutionModel.ecore#//RMRequiredElements">
    <eStructuralFeatures xsi:type="ecore:EReference" name="requiredNodes" upperBound="-1"
        eType="ecore:EClass ../../org.hyperflex.componentmodels.ros.model/models/rosComponentModel.ecore#//Node"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requiredTopicConnections"
        upperBound="-1" eType="#//ROSTopicConnection" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requiredServiceConnections"
        upperBound="-1" eType="ecore:EClass ../../org.hyperflex.componentmodels.ros.model/models/rosComponentModel.ecore#//Wire"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ROSTemplateSystemModel" eSuperTypes="../../org.hyperflex.resolutionmodels.model/models/resolutionModel.ecore#//TemplateSystemModel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="system" lowerBound="1"
        eType="ecore:EClass ../../org.hyperflex.componentmodels.ros.model/models/rosComponentModel.ecore#//System"/>
  </eClassifiers>
</ecore:EPackage>
